### ISSUE TITLE
ssh2 fails to build

### ISSUE THREAD

**Issue by rkeene** [datanoise/ssh2.cr#2]
```
$ make
crystal build blah.cr
Error in ./blah.cr:2: while requiring "ssh2/ssh2"

require "ssh2/ssh2"
^

in ./libs/ssh2/ssh2.cr:109: while requiring "./session"

require "./session"
^

Syntax error in ./libs/ssh2/session.cr:339: unexpected token: ::

        buf :: UInt8[1024]
            ^

make: *** [blah] Error 1
$
```

This may be related to a change in the Crystal syntax in 0.11.0:
0.11.0

> (breaking change) Syntax for type declarations changed from var :: Type to var : Type. The old syntax is still allowed but will be deprecated in the next version (run crystal tool format to automatically fix this)

**Comment by datanoise** [comment]
upgraded to latest crystal
