### ISSUE TITLE
Key from String?

### ISSUE THREAD

**Issue by crisward** [datanoise/ssh2.cr#9]
I'd like to login from keys stored in a database. I currently have keys in a database table, encrypted. I'd like to decrypt them in memory, then login to a remote server.

Is this possible with this library, or do they key need to be written to disk? Looking at the source code it looks like you're just passing a filename. But if you have any clues if it's possible to achieve this is would be really useful.

**Comment by datanoise** [comment]
I think `Session#login_with_data` method could be useful in such situations.

**Comment by crisward** [comment]
Thanks for the rapid response, that worked!
